#BASE IMAGE
FROM ubuntu
#MAINTAINER
MAINTAINER bhavleen kaur
#INSTALL UPDATES
RUN apt-get update
#NECESSORY TOOLS
RUN apt-get install -y vim wget curl net-tools
#INSTALL NGINX
RUN apt-get install -y nginx
#REMOVE THE DEFAULT NGINX CONF FILE
#COPY THE CONF FILE FROM CURRENT DIRECTORY
RUN mkdir /etc/nginx/logs
#EXPOSE PORTS
EXPOSE 80
#SET THE DEFAULT COMMAND TO EXECUTE
CMD ["NGINX"]


